"""add qr code

Revision ID: 45e41188931a
Revises: 87ae56d6a929
Create Date: 2025-01-24 10:47:20.194778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e41188931a'
down_revision: Union[str, None] = '87ae56d6a929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportWaste', sa.Column('qrCode', sa.String(), nullable=True))
    op.add_column('reportWaste', sa.Column('qrCodeVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportWaste', 'qrCodeVerified')
    op.drop_column('reportWaste', 'qrCode')
    # ### end Alembic commands ###
