"""add column

Revision ID: 872b53231843
Revises: 6bc549f30cec
Create Date: 2025-01-25 15:57:11.095477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872b53231843'
down_revision: Union[str, None] = '6bc549f30cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportWaste', sa.Column('collectedBy', sa.String(), nullable=True))
    op.add_column('reportWaste', sa.Column('collectedAt', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'reportWaste', 'collectors', ['collectedBy'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reportWaste', type_='foreignkey')
    op.drop_column('reportWaste', 'collectedAt')
    op.drop_column('reportWaste', 'collectedBy')
    # ### end Alembic commands ###
