"""recycly table

Revision ID: df4fb2958e15
Revises: d510c8b780d2
Create Date: 2025-01-15 16:41:02.473235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df4fb2958e15'
down_revision: Union[str, None] = 'd510c8b780d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycleInfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waste_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycleInfo')
    # ### end Alembic commands ###
