"""seeding data

Revision ID: ebdb26119bbd
Revises: 332118a6aa59
Create Date: 2025-01-17 01:20:51.655434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from utils import hash

# revision identifiers, used by Alembic.
revision: str = 'ebdb26119bbd'
down_revision: Union[str, None] = '332118a6aa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = sa.sql.table(
        "users",
        sa.Column("email", sa.String),
        sa.Column("phone", sa.String),
        sa.Column("name", sa.String),
        sa.Column("password", sa.String),
        sa.Column("role", sa.String),
        sa.Column("userName", sa.String),
        sa.Column("address", sa.String),
        sa.Column("image", sa.String),
    )
    op.bulk_insert(
        user_table,
        [
            {
                "email": "dibbyoroy7@gmail.com",
                "phone": "1234567890",
                "name": "Dibbyo Roy",
                "password": hash("1234"),
                "role": "ADMIN",
                "userName": "dibbyoroy7",
                "address": "Kolkata",
                "image": "https://www.google.com",
            }
        ],
    )

    resident_table = sa.sql.table(
        "residents",
        sa.Column("email", sa.String),
        sa.Column("phone", sa.String),
        sa.Column("name", sa.String),
        sa.Column("reward", sa.Integer),
    )

    op.bulk_insert(
        resident_table,
        [
            {
                "email": "dibbyoroy7@gmail.com",
                "phone": "1234567890",
                "name": "Dibbyo Roy",
                "reward": 0,
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DELETE FROM users WHERE email = 'dibbyoroy7@gmail.com'")
    op.execute("DELETE FROM residents WHERE email = 'dibbyoroy7@gmail.com'")
